version: "3"
services:
  nginx:
    container_name: "prsk-nginx"
    build: ./docker/nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./app:/var/www/html:cached
      - ./docker/logs/nginx:/var/log/nginx/:cached
    tty: true
    platform: linux/amd64

  app:
    container_name: "prsk-app"
    build: ./docker/php
    ports:
      - "5173:5173"
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/logs/app:/var/log/zsh/:cached
    platform: linux/amd64

  db:
    container_name: "prsk-db"
    build: ./docker/db
    volumes:
      - ./docker/db/data:/var/lib/mysql:cached
      - ./docker/logs/db:/var/log/mysql:cached
    ports:
      - "3307:3307"
    expose:
      - "3307"
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/amd64
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_DATABASE: "prsk"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_TCP_PORT: "3307"

  mail:
    container_name: "prsk-mail"
    build: ./docker/mail
    ports:
      - "8025:8025"
      - "1025:1025"
    platform: linux/amd64

  redis:
    container_name: "prsk-redis"
    image: redis:alpine
    ports:
      - 16379:6379
    platform: linux/amd64
