version: '3'
services:
  web:
    container_name: prsk_web
    build: ./docker/web
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html/prsk:cached
      - ./docker/logs/httpd:/var/log/httpd:cached
    depends_on:
      - db

  db:
    container_name: prsk_db
    build: ./docker/db
    volumes:
      - ./docker/db/data:/var/lib/mysql:cached
      - ./docker/logs/db:/var/log/mysql:cached
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_DATABASE: 'prsk'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'

  mail:
    container_name: prsk_mail
    build: ./docker/mail
    ports:
      - "8025:8025"
      - "1025:1025"
