version: '3'
services:
  nginx:
    container_name: "prsk-nginx"
    build: ./docker/nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./app:/var/www/html:cached
      - ./docker/logs/nginx:/var/log/nginx/:cached

  app:
    container_name: "prsk-app"
    build: ./docker/php
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  db:
    container_name: "prsk-db"
    build: ./docker/db
    volumes:
      - ./docker/db/data:/var/lib/mysql:cached
      - ./docker/logs/db:/var/log/mysql:cached
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_DATABASE: 'prsk'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'

  mail:
    container_name: "prsk-mail"
    build: ./docker/mail
    ports:
      - "8025:8025"
      - "1025:1025"

  redis:
    container_name: "prsk-redis"
    image: redis:alpine
    ports:
      - 16379:6379
