<?php

namespace Database\Seeders;

use App\Enums\Attribute;
use App\Enums\EventType;
use App\Models\Event;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $records = [
            [
                'starts_at' => '2020-10-09 15:00:00',
                'ends_at' => '2020-10-18 20:59:59',
                'name' => "雨上がりの一番星",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::MYSTERIOUS,
                'tune_id' => 46,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2020-10-20 15:00:00',
                'ends_at' => '2020-10-29 20:59:59',
                'name' => "囚われのマリオネット",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::COOL,
                'tune_id' => 48,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2020-10-31 15:00:00',
                'ends_at' => '2020-11-07 20:59:59',
                'name' => "全力！ワンダーハロウィン！",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::HAPPY,
                'tune_id' => 51,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2020-11-09 15:00:00',
                'ends_at' => '2020-11-17 20:59:59',
                'name' => "走れ！体育祭！～実行委員は大忙し～",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::PURE,
                'tune_id' => null,
                'is_key_story' => false,
                'story_chapter' => null,
            ],
            [
                'starts_at' => '2020-11-19 15:00:00',
                'ends_at' => '2020-11-28 20:59:59',
                'name' => "ここからRE:START！",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::CUTE,
                'tune_id' => 53,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2020-11-30 15:00:00',
                'ends_at' => '2020-12-08 20:59:59',
                'name' => "いつか、背中あわせのリリックを",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::COOL,
                'tune_id' => 58,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2020-12-10 15:00:00',
                'ends_at' => '2020-12-18 20:59:59',
                'name' => "KAMIKOU FESTIVAL！",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::MYSTERIOUS,
                'tune_id' => null,
                'is_key_story' => false,
                'story_chapter' => null,
            ],
            [
                'starts_at' => '2020-12-20 15:00:00',
                'ends_at' => '2020-12-29 20:59:59',
                'name' => "聖なる夜に、この歌声を",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::CUTE,
                'tune_id' => 60,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2020-12-31 15:00:00',
                'ends_at' => '2021-01-08 20:59:59',
                'name' => "セカイのハッピーニューイヤー！",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::PURE,
                'tune_id' => null,
                'is_key_story' => false,
                'story_chapter' => null,
            ],
            [
                'starts_at' => '2021-01-10 15:00:00',
                'ends_at' => '2021-01-19 20:59:59',
                'name' => "揺れるまま、でも君は前へ",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::HAPPY,
                'tune_id' => 71,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2021-01-21 15:00:00',
                'ends_at' => '2021-01-29 20:59:59',
                'name' => "Color of Myself！",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::COOL,
                'tune_id' => 74,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2021-01-31 15:00:00',
                'ends_at' => '2021-02-07 20:59:59',
                'name' => "Period of NOCTURNE",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::MYSTERIOUS,
                'tune_id' => 75,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2021-02-09 15:00:00',
                'ends_at' => '2021-02-16 20:59:59',
                'name' => "響くトワイライトパレード",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::CUTE,
                'tune_id' => null,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2021-02-18 15:00:00',
                'ends_at' => '2021-02-26 20:59:59',
                'name' => "満たされないペイルカラー",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::HAPPY,
                'tune_id' => 81,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2021-02-28 15:00:00',
                'ends_at' => '2021-03-08 20:59:59',
                'name' => "スマイルオブドリーマー",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::MYSTERIOUS,
                'tune_id' => 82,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2021-03-10 15:00:00',
                'ends_at' => '2021-03-20 20:59:59',
                'name' => "天馬さんちのひな祭り",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::PURE,
                'tune_id' => null,
                'is_key_story' => false,
                'story_chapter' => null,
            ],
            [
                'starts_at' => '2021-03-22 15:00:00',
                'ends_at' => '2021-03-30 20:59:59',
                'name' => "届け！HOPEFUL STAGE♪",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::HAPPY,
                'tune_id' => 88,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2021-04-01 15:00:00',
                'ends_at' => '2021-04-09 20:59:59',
                'name' => "君と歌う、桜舞う世界で",
                'type' => EventType::CHEERFUL,
                'attribute' => Attribute::PURE,
                'tune_id' => null,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2021-04-11 15:00:00',
                'ends_at' => '2021-04-19 20:59:59',
                'name' => "シークレット・ディスタンス",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::CUTE,
                'tune_id' => 91,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2021-04-21 15:00:00',
                'ends_at' => '2021-04-28 20:59:59',
                'name' => "Resonate with you",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::COOL,
                'tune_id' => 92,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2021-04-30 15:00:00',
                'ends_at' => '2021-05-08 20:59:59',
                'name' => "STRAY BAD DOG",
                'type' => EventType::CHEERFUL,
                'attribute' => Attribute::HAPPY,
                'tune_id' => 96,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2021-05-10 15:00:00',
                'ends_at' => '2021-05-19 20:59:59',
                'name' => "お悩み聞かせて！わくわくピクニック",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::PURE,
                'tune_id' => null,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2021-05-21 15:00:00',
                'ends_at' => '2021-05-29 20:59:59',
                'name' => "頑張るあなたにBreak Time！",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::MYSTERIOUS,
                'tune_id' => 98,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2021-05-31 15:00:00',
                'ends_at' => '2021-06-09 20:59:59',
                'name' => "純白の貴方へ、誓いの歌を！",
                'type' => EventType::CHEERFUL,
                'attribute' => Attribute::CUTE,
                'tune_id' => null,
                'is_key_story' => false,
                'story_chapter' => null,
            ],
            [
                'starts_at' => '2021-06-11 15:00:00',
                'ends_at' => '2021-06-19 20:59:59',
                'name' => "ワンダーマジカルショウタイム！",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::COOL,
                'tune_id' => 102,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2021-06-21 15:00:00',
                'ends_at' => '2021-06-28 20:59:59',
                'name' => "カーネーション・リコレクション",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::MYSTERIOUS,
                'tune_id' => 103,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2021-06-30 15:00:00',
                'ends_at' => '2021-07-07 20:59:59',
                'name' => "Unnamed Harmony",
                'type' => EventType::CHEERFUL,
                'attribute' => Attribute::HAPPY,
                'tune_id' => 105,
                'is_key_story' => true,
                'story_chapter' => 2,
            ],
            [
                'starts_at' => '2021-07-09 15:00:00',
                'ends_at' => '2021-07-18 20:59:59',
                'name' => "Awakening Beat",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::CUTE,
                'tune_id' => 106,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2021-07-20 15:00:00',
                'ends_at' => '2021-07-29 20:59:59',
                'name' => "夏祭り、鳴り響く音は",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::COOL,
                'tune_id' => null,
                'is_key_story' => false,
                'story_chapter' => null,
            ],
            [
                'starts_at' => '2021-07-31 15:00:00',
                'ends_at' => '2021-08-08 20:59:59',
                'name' => "きっと最高のsummer！",
                'type' => EventType::CHEERFUL,
                'attribute' => Attribute::PURE,
                'tune_id' => null,
                'is_key_story' => false,
                'story_chapter' => null,
            ],
            [
                'starts_at' => '2021-08-10 15:00:00',
                'ends_at' => '2021-08-18 20:59:59',
                'name' => "ハッピー・ラブリー・エブリデイ！",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::MYSTERIOUS,
                'tune_id' => 112,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2021-08-20 15:00:00',
                'ends_at' => '2021-08-29 20:59:59',
                'name' => "マーメイドにあこがれて",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::PURE,
                'tune_id' => 113,
                'is_key_story' => true,
                'story_chapter' => 2,
            ],
            [
                'starts_at' => '2021-08-31 15:00:00',
                'ends_at' => '2021-09-08 20:59:59',
                'name' => "ふたり、月うさぎ",
                'type' => EventType::CHEERFUL,
                'attribute' => Attribute::CUTE,
                'tune_id' => null,
                'is_key_story' => false,
                'story_chapter' => null,
            ],
            [
                'starts_at' => '2021-09-10 15:00:00',
                'ends_at' => '2021-09-19 20:59:59',
                'name' => "Knock the Future!!",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::MYSTERIOUS,
                'tune_id' => 116,
                'is_key_story' => true,
                'story_chapter' => 2,
            ],
            [
                'starts_at' => '2021-09-21 15:00:00',
                'ends_at' => '2021-09-29 20:59:59',
                'name' => "灯のミラージュ",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::HAPPY,
                'tune_id' => 118,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2021-10-01 15:00:00',
                'ends_at' => '2021-10-09 20:59:59',
                'name' => "スクランブル・ファンフェスタ！",
                'type' => EventType::CHEERFUL,
                'attribute' => Attribute::PURE,
                'tune_id' => null,
                'is_key_story' => false,
                'story_chapter' => null,
            ],
            [
                'starts_at' => '2021-10-11 15:00:00',
                'ends_at' => '2021-10-19 20:59:59',
                'name' => "Bout for Beside You",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::COOL,
                'tune_id' => 134,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2021-10-21 15:00:00',
                'ends_at' => '2021-10-29 20:59:59',
                'name' => "Revival my dream",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::HAPPY,
                'tune_id' => 136,
                'is_key_story' => true,
                'story_chapter' => 2,
            ],
            [
                'starts_at' => '2021-10-31 15:00:00',
                'ends_at' => '2021-11-09 20:59:59',
                'name' => "ボクのあしあと キミのゆくさき",
                'type' => EventType::CHEERFUL,
                'attribute' => Attribute::CUTE,
                'tune_id' => 139,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2021-11-11 15:00:00',
                'ends_at' => '2021-11-18 20:59:59',
                'name' => "揺るがぬ想い、今言葉にして",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::COOL,
                'tune_id' => 141,
                'is_key_story' => true,
                'story_chapter' => 2,
            ],
            [
                'starts_at' => '2021-11-20 15:00:00',
                'ends_at' => '2021-11-28 20:59:59',
                'name' => "バディ・ファニー・スペンドタイム♪",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::HAPPY,
                'tune_id' => null,
                'is_key_story' => false,
                'story_chapter' => null,
            ],
            [
                'starts_at' => '2021-11-30 15:00:00',
                'ends_at' => '2021-12-08 20:59:59',
                'name' => "交わる旋律 灯るぬくもり",
                'type' => EventType::CHEERFUL,
                'attribute' => Attribute::CUTE,
                'tune_id' => null,
                'is_key_story' => false,
                'story_chapter' => null,
            ],
            [
                'starts_at' => '2021-12-10 15:00:00',
                'ends_at' => '2021-12-18 20:59:59',
                'name' => "MOREMOREMakingXmas",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::MYSTERIOUS,
                'tune_id' => 147,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2021-12-20 15:00:00',
                'ends_at' => '2021-12-29 20:59:59',
                'name' => "Same Dreams,Same Colors",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::PURE,
                'tune_id' => 156,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2021-12-31 15:00:00',
                'ends_at' => '2022-01-10 20:59:59',
                'name' => "祈りの先 願う明日は",
                'type' => EventType::CHEERFUL,
                'attribute' => Attribute::CUTE,
                'tune_id' => null,
                'is_key_story' => false,
                'story_chapter' => null,
            ],
            [
                'starts_at' => '2022-01-12 15:00:00',
                'ends_at' => '2022-01-19 20:59:59',
                'name' => "POP IN MY HEART!!",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::COOL,
                'tune_id' => 157,
                'is_key_story' => true,
                'story_chapter' => 2,
            ],
            [
                'starts_at' => '2022-01-21 15:00:00',
                'ends_at' => '2022-01-29 20:59:59',
                'name' => "いつか、絶望の底から",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::PURE,
                'tune_id' => 163,
                'is_key_story' => true,
                'story_chapter' => 2,
            ],
            [
                'starts_at' => '2022-01-31 15:00:00',
                'ends_at' => '2022-02-07 20:59:59',
                'name' => "秘密の♡バレンタイン大作戦！",
                'type' => EventType::CHEERFUL,
                'attribute' => Attribute::HAPPY,
                'tune_id' => null,
                'is_key_story' => false,
                'story_chapter' => null,
            ],
            [
                'starts_at' => '2022-02-09 15:00:00',
                'ends_at' => '2022-02-16 20:59:59',
                'name' => "Legend still vivid",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::MYSTERIOUS,
                'tune_id' => 164,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2022-02-18 15:00:00',
                'ends_at' => '2022-02-26 20:59:59',
                'name' => "あの日、空は遠かった",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::PURE,
                'tune_id' => 170,
                'is_key_story' => true,
                'story_chapter' => 2,
            ],
            [
                'starts_at' => '2022-02-28 15:00:00',
                'ends_at' => '2022-03-09 20:59:59',
                'name' => "怪盗紳士のハラハラ！？ホワイトデー",
                'type' => EventType::CHEERFUL,
                'attribute' => Attribute::MYSTERIOUS,
                'tune_id' => null,
                'is_key_story' => false,
                'story_chapter' => null,
            ],
            [
                'starts_at' => '2022-03-11 15:00:00',
                'ends_at' => '2022-03-18 20:59:59',
                'name' => "Cast Spell on You",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::PURE,
                'tune_id' => 180,
                'is_key_story' => true,
                'story_chapter' => 2,
            ],
            [
                'starts_at' => '2022-03-20 15:00:00',
                'ends_at' => '2022-03-28 20:59:59',
                'name' => "空白のキャンバスに描く私は",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::COOL,
                'tune_id' => 184,
                'is_key_story' => true,
                'story_chapter' => 2,
            ],
            [
                'starts_at' => '2022-03-30 15:00:00',
                'ends_at' => '2022-04-09 20:59:59',
                'name' => "セカイの桜、つながる想い",
                'type' => EventType::CHEERFUL,
                'attribute' => Attribute::HAPPY,
                'tune_id' => null,
                'is_key_story' => false,
                'story_chapter' => null,
            ],
            [
                'starts_at' => '2022-04-11 15:00:00',
                'ends_at' => '2022-04-19 20:59:59',
                'name' => "まばゆい光のステージで",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::CUTE,
                'tune_id' => 185,
                'is_key_story' => true,
                'story_chapter' => 2,
            ],
            [
                'starts_at' => '2022-04-21 15:00:00',
                'ends_at' => '2022-04-28 20:59:59',
                'name' => "Live with memories",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::MYSTERIOUS,
                'tune_id' => 190,
                'is_key_story' => true,
                'story_chapter' => 2,
            ],
            [
                'starts_at' => '2022-04-30 15:00:00',
                'ends_at' => '2022-05-08 20:59:59',
                'name' => "つなぐPainful Hope",
                'type' => EventType::CHEERFUL,
                'attribute' => Attribute::COOL,
                'tune_id' => 194,
                'is_key_story' => true,
                'story_chapter' => 2,
            ],
            [
                'starts_at' => '2022-05-10 15:00:00',
                'ends_at' => '2022-05-18 20:59:59',
                'name' => "白熱！神高応援団！",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::COOL,
                'tune_id' => null,
                'is_key_story' => false,
                'story_chapter' => null,
            ],
            [
                'starts_at' => '2022-05-20 15:00:00',
                'ends_at' => '2022-05-29 20:59:59',
                'name' => "THE POWER OF UNITY",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::CUTE,
                'tune_id' => 197,
                'is_key_story' => true,
                'story_chapter' => 1,
            ],
            [
                'starts_at' => '2022-05-31 15:00:00',
                'ends_at' => '2022-06-08 20:59:59',
                'name' => "青空に願うユア・ハピネス！",
                'type' => EventType::CHEERFUL,
                'attribute' => Attribute::PURE,
                'tune_id' => null,
                'is_key_story' => false,
                'story_chapter' => null,
            ],
            [
                'starts_at' => '2022-06-10 15:00:00',
                'ends_at' => '2022-06-18 20:59:59',
                'name' => "迷い子の手を引く、そのさきは",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::COOL,
                'tune_id' => 199,
                'is_key_story' => true,
                'story_chapter' => 2,
            ],
            [
                'starts_at' => '2022-06-20 15:00:00',
                'ends_at' => '2022-06-28 20:59:59',
                'name' => "絶体絶命！？アイランドパニック！",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::HAPPY,
                'tune_id' => 203,
                'is_key_story' => true,
                'story_chapter' => 2,
            ],
            [
                'starts_at' => '2022-06-30 15:00:00',
                'ends_at' => '2022-07-09 20:59:59',
                'name' => "みんなでエンジョイ！スポジョイパーク",
                'type' => EventType::CHEERFUL,
                'attribute' => Attribute::HAPPY,
                'tune_id' => null,
                'is_key_story' => false,
                'story_chapter' => null,
            ],
            [
                'starts_at' => '2022-07-11 15:00:00',
                'ends_at' => '2022-07-19 20:59:59',
                'name' => "The Vivid Old Tale",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::MYSTERIOUS,
                'tune_id' => 208,
                'is_key_story' => true,
                'story_chapter' => 2,
            ],
            [
                'starts_at' => '2022-07-21 15:00:00',
                'ends_at' => '2022-07-29 20:59:59',
                'name' => "No seek No find",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::CUTE,
                'tune_id' => 209,
                'is_key_story' => true,
                'story_chapter' => 2,
            ],
            [
                'starts_at' => '2022-07-31 15:00:00',
                'ends_at' => '2022-08-08 20:59:59',
                'name' => "close game/OFFLINE",
                'type' => EventType::CHEERFUL,
                'attribute' => Attribute::CUTE,
                'tune_id' => null,
                'is_key_story' => false,
                'story_chapter' => null,
            ],
            [
                'starts_at' => '2022-08-10 15:00:00',
                'ends_at' => '2022-08-18 20:59:59',
                'name' => "青空の先、輝きを追いかけて",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::COOL,
                'tune_id' => 212,
                'is_key_story' => true,
                'story_chapter' => 2,
            ],
            [
                'starts_at' => '2022-08-20 15:00:00',
                'ends_at' => '2022-08-29 20:59:59',
                'name' => "そしていま、リボンを結んで",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::CUTE,
                'tune_id' => 216,
                'is_key_story' => true,
                'story_chapter' => 2,
            ],
            [
                'starts_at' => '2022-08-31 15:00:00',
                'ends_at' => '2022-09-07 20:59:59',
                'name' => "Don't lose faith!",
                'type' => EventType::CHEERFUL,
                'attribute' => Attribute::PURE,
                'tune_id' => 218,
                'is_key_story' => true,
                'story_chapter' => 2,
            ],
            [
                'starts_at' => '2022-09-09 15:00:00',
                'ends_at' => '2022-09-18 20:59:59',
                'name' => "好きを描いて♪レインボーキャンバス",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::MYSTERIOUS,
                'tune_id' => null,
                'is_key_story' => false,
                'story_chapter' => null,
            ],
            [
                'starts_at' => '2022-09-20 15:00:00',
                'ends_at' => '2022-09-28 20:59:59',
                'name' => "Walk on and on",
                'type' => EventType::MARATHON,
                'attribute' => Attribute::COOL,
                'tune_id' => 221,
                'is_key_story' => true,
                'story_chapter' => 2,
            ],
            [
                'starts_at' => '2022-09-30 15:00:00',
                'ends_at' => '2022-10-10 20:59:59',
                'name' => "この祭に 夕闇色も",
                'type' => EventType::CHEERFUL,
                'attribute' => Attribute::PURE,
                'tune_id' => null,
                'is_key_story' => false,
                'story_chapter' => null,
            ],
        ];

        DB::table('events')->truncate();
        foreach ($records as $record) {
            $entity = new Event();
            foreach ($record as $key => $value) {
                $entity->setAttribute($key, $value);
            }
            $entity->save();
        }
    }
}
