<?php

namespace Database\Seeders;

use App\Models\Icon;
use Illuminate\Database\Seeder;

class IconsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $records = [
            [
                'path' => 'icons',
                'name' => 'xTyK0xuSGlylFEglQlTN72TYLr6SFM0nZ52hS473.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_01_icon_01_miku_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 't981hh94frFGwX6TImzT2VMKAeQcDS7MqHd8LJsD.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_01_icon_02_rin_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'Co21ryVDbcOtWEBgBiAJakD7QoL1aPzdRKP3zmha.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_01_icon_03_len_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'Hvze42wsr2hX0Nb0NwK1xspo638g4hvnbnBdoDCj.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_01_icon_04_luka_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'pVYv7br411yLF3t82x5PXDUs4N7BukHqEQsjQD0u.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_01_icon_05_meiko_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'SUqYF2gFzWo68McSYaGhCvpTHWvSxOypngoKnpPn.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_01_icon_06_kaito_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'HR6GeKAwHksofVnQc7A8hNuxSCXrTyDHZkQlLLKR.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_02_icon_01_ichica_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 's0Copc6hF6pndUQDfO4smhwo4cdrkMjtGszkgtPG.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_02_icon_02_saki_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'uQXRsvunOTgw3wQQtpvvIVpxKOpuMdkL5EgaEgf2.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_02_icon_03_honami_01.png',
            ],
            [
                'path' => 'icons',
                'name' => '1SBzhpt0suMEOWZBUv3TBjm63Wu8REohFaBmBNJV.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_02_icon_04_shiho_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'v0zVyZ8j1anflre20hPjNKN2TIFor1p8ZwmIsuz1.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_02_icon_05_miku_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'AYLVj3fq90UNL3BPIYjJrbHBX4rz2SjTSfUBr3vP.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_02_icon_06_luka_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'C84dJp0goEl6JI72HUXwSSf3eHYDhMZmVP0ZrdBQ.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_03_icon_01_minori_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'giqvvindh59roVanZMqJlHECqCxyPyfHvAzTLE3t.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_03_icon_02_haruka_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'nAirNd1mdec6fEaj8CZ2htSJjHhW2a9Vt2NTZwSS.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_03_icon_03_airi_01.png',
            ],
            [
                'path' => 'icons',
                'name' => '3GjTGl5VC1ScsOPViartAMOiQb7e6slYAEWP5GTw.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_03_icon_04_shizuku_01.png',
            ],
            [
                'path' => 'icons',
                'name' => '8Wb7lErwH4SBsihtMdn3vnusxGFEwk6LSC6JQPOP.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_03_icon_05_miku_01.png',
            ],
            [
                'path' => 'icons',
                'name' => '1q2mpQ3lCfoiQAHb3p0XgVSzAPcv6QXur0K7et7F.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_03_icon_06_rin_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'o7WnOY7gm5Pk862afBcHfMucoYHEQMDHWMwcTu5Y.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_04_icon_01_kohane_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'GdUU9dGOCAO87AGL8BjKx05odZVSizDKEs6QONSC.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_04_icon_02_an_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'NJzBgePQxEh4go0fnK6VRP0wpt9nCKaANXGnG2Vf.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_04_icon_03_akito_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'rBkIrFDds60ctTHevZi0sgrHxbcocrqzB0haV3v0.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_04_icon_04_toya_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'KGTKqXZFQFZD1ysCg3eIKHQ78McL5d2J1EYZR2Z7.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_04_icon_05_miku_01.png',
            ],
            [
                'path' => 'icons',
                'name' => '9iRbYv3LTWS8WuzoC86ZfsvnpNgfO0a1git36Y0L.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_04_icon_06_len_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'Wjeonlt63lyusxLNjEUvFF8aOVi0CHK4GzhNIXT6.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_04_icon_07_meiko_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'zG85hSgyc81XgKIYgyCKYMpkBbHJAXVqqeWL6YkY.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_05_icon_01_tsukasa_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'FxSfZASZQLF50KOlPSWE9cnt7bvyPitxPyNoJ0U7.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_05_icon_02_emu_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'VF5XY33siVIL7CozXEuYgtXtynUHcKIr6Cyaasxd.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_05_icon_03_nene_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'wq7RZuBvA5RZ3ZIovZVuxVjZFyNerwjUC6EgkS0H.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_05_icon_04_rui_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'Zxswp73uxH0vH7No3i7YByGPDsLUuUK7TmE7dSWI.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_05_icon_05_miku_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'WeXvaathnoswNuZbw7XPbXsjQ9kzQvTRsAHPXul3.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_05_icon_06_kaito_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'mjHBgT1oG3wtJrafHqxL44ujHdEU276HZykFV1Ui.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_06_icon_01_kanade_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'k81P7LWTgcgc6XdkSWgUXodz4nkZp8xkur0hktaF.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_06_icon_02_mafuyu_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'pmWkksJR5PODzwDiShxvqpElcxSApOUd7v6pD1qH.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_06_icon_03_ena_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'HUeP4PWWhNaT6XBldJWOUSlrlYowAQDNkeFCIeob.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_06_icon_04_mizuki_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'VE0M4O8Crwz37tY4uRJ6O7SIpMkebsN3dqbihsmt.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_06_icon_05_miku_01.png',
            ],
            [
                'path' => 'icons',
                'name' => 'P8IS5VkIeeMEbautUwLiWKAfDM17nYED5dymSF6a.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_02_icon_01_ichica_02.png',
            ],
            [
                'path' => 'icons',
                'name' => '8ngFOaTkPTyNhDpuRvmpBR9eAuuKdGz1szlPWvBP.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_02_icon_02_saki_02.png',
            ],
            [
                'path' => 'icons',
                'name' => '828WDHHiGKF8ka3qCWIBShFvzqltwCzC5kPzdi3h.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_02_icon_03_honami_02.png',
            ],
            [
                'path' => 'icons',
                'name' => 'AWJOWV4O1yBO9z2Iv7yYU0yc5JGaHQEmQCv7Cd7a.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_02_icon_04_shiho_02.png',
            ],
            [
                'path' => 'icons',
                'name' => 'cQ5UJaQXnWannDxWQKtvklOjrgn6RV3n1OyVgHJO.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_02_icon_05_miku_02.png',
            ],
            [
                'path' => 'icons',
                'name' => 'eZmx1Nn9ugVQzAxaBIp9VHSC8HVAPNd1FyBt4NJt.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_02_icon_06_luka_02.png',
            ],
            [
                'path' => 'icons',
                'name' => 'ikA9uAoUdkbJwAqJLSMq18ZwSE0gUpMSaPWXGS4d.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_03_icon_01_minori_02.png',
            ],
            [
                'path' => 'icons',
                'name' => '3VtfCeIkuPjAOafxbSuewSXI6SDWxYQ5H4HDg7yP.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_03_icon_02_haruka_02.png',
            ],
            [
                'path' => 'icons',
                'name' => 'blRSN9bt6HJ9Uq7CnPoLCNXV5era1e8H7jjXbETN.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_03_icon_03_airi_02.png',
            ],
            [
                'path' => 'icons',
                'name' => '84iH8xO5uzhmO5wIbNSGhKgvfraEDLBD94qIZdTy.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_03_icon_04_shizuku_02.png',
            ],
            [
                'path' => 'icons',
                'name' => 'R2JxqebxiTSqrstdpHpJ7BO6RDFr05xm96YKdptz.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_03_icon_05_miku_02.png',
            ],
            [
                'path' => 'icons',
                'name' => '9sd6cVbnpzhPhLQqkDppRcwPINkHwlq8LlA8toAJ.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_03_icon_06_rin_02.png',
            ],
            [
                'path' => 'icons',
                'name' => 'PAg4VSXZEO605qFCOff8c8eoG6fGM6Vy1R5oSNUg.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_04_icon_01_kohane_02.png',
            ],
            [
                'path' => 'icons',
                'name' => 'vCQSAElKDAgwibBlRs0gHMpY9bHYafly7WIpsQeT.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_04_icon_02_an_02.png',
            ],
            [
                'path' => 'icons',
                'name' => 'VgCwWAnB0TLk5OCflTcnJLhn6mTew20d1Dn2jNqr.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_04_icon_03_akito_02.png',
            ],
            [
                'path' => 'icons',
                'name' => 'SOVTnShba7RJIDH6Q9XlriwyAtBzoSkL8ZJ3y0We.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_04_icon_04_toya_02.png',
            ],
            [
                'path' => 'icons',
                'name' => 'ZntcWME0qYlpt19jN4bZk9Iyq9dMRY2gCmpES3a3.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_04_icon_05_miku_02.png',
            ],
            [
                'path' => 'icons',
                'name' => '3VdbOqE0UiQpXUNCayHhg9jJ9FKvhk0jPvjd3s4R.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_04_icon_06_len_02.png',
            ],
            [
                'path' => 'icons',
                'name' => 'AyZHREhfaZBdtPLurYK1tsJTJT1l1OUEEtIyTCUe.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_04_icon_07_meiko_02.png',
            ],
            [
                'path' => 'icons',
                'name' => 'sf0ReUnvaZpkMcepfMpvGJCNBn16lGBiJsgCzNiy.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_05_icon_01_tsukasa_02.png',
            ],
            [
                'path' => 'icons',
                'name' => 'ASFQ5QVHdCVERxyPUJQhah1ImMaGPo3BUIg4TMAA.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_05_icon_02_emu_02.png',
            ],
            [
                'path' => 'icons',
                'name' => '41vj35PHzaCazGgWZmOctcNglovBf2thWidjLL6O.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_05_icon_03_nene_02.png',
            ],
            [
                'path' => 'icons',
                'name' => 'eEkVV4niIEWYT31C7yqQ3ZAUsIgcKsMnz7hOYESE.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_05_icon_04_rui_02.png',
            ],
            [
                'path' => 'icons',
                'name' => 'Gw4CCo33KIG7rvR1le5YqiGzOJiswlYe345fG8dc.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_05_icon_05_miku_02.png',
            ],
            [
                'path' => 'icons',
                'name' => 'odHWtKytztlmclaj7X1lAwshIi9pd4UADl4CuDg8.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_05_icon_06_kaito_02.png',
            ],
            [
                'path' => 'icons',
                'name' => '9fHUhaOhMwy45qhBhulUfNuEX7SNhkyHdFZ5SLRx.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_06_icon_01_kanade_02.png',
            ],
            [
                'path' => 'icons',
                'name' => 'PA3rt45NG0ssrybTfKI0bamRpcbEzy9aDZ42AAef.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_06_icon_02_mafuyu_02.png',
            ],
            [
                'path' => 'icons',
                'name' => 'oNGiYPV0yff24wZPjYBmn3oXsiuevFy3LvTbExTt.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_06_icon_03_ena_02.png',
            ],
            [
                'path' => 'icons',
                'name' => 'WnGmJN3iiEOCS8f679JMjUW5mImrq2A92dYNWq3e.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_06_icon_04_mizuki_02.png',
            ],
            [
                'path' => 'icons',
                'name' => '5GGxIY0DQjQjUX2cstGUO00Rlf87Oq3d0kxxQiN6.png',
                'mime_type' => 'image/png',
                'extension' => 'png',
                'label' => 'unit_06_icon_05_miku_02.png',
            ],
            [
                'path' => 'icons',
                'name' => 'dQfBQX68mRQcwwlNmx6E2hJAscAtj9daZsmKSn6Y.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_02_icon_01_ichica_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'Xp3XZuyh4rtRVitByyRA0rx4tdjhTGmpvCLHrgm9.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_02_icon_02_saki_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'bglEVQilR2voRvnY9r9txb4hunZYz5TyKRirQF9A.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_02_icon_03_honami_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'y66ql2iTUlGQsxzTdycN0JYGKmciGYymGTOOQjP9.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_02_icon_04_shiho_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'yZ71hxR9L64gNbezLXMQmtWfvjTB1Ed018yvPJhq.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_02_icon_05_miku_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'KkfEc7jHOmb1d5PwUqPwALWmWrjVcg1OUbaCoyku.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_02_icon_06_luka_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'hboSNafgyMEGlHyGHqkaDmWyL9Ks1Kyi7Ct0xzxy.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_03_icon_01_minori_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'JGmh1lXIkO4qA6ML3KKxyqXGmKbzwxGe4Wz9MzHi.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_03_icon_02_haruka_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'ZDoZx1VWlyoVBTWkSSCevSYZMlZPzm1L85znQoes.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_03_icon_03_airi_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'R36Njx8xZ1dZoR1rSWgUrAgJ2BLhuKa5LN2jSD6e.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_03_icon_04_shizuku_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'MvdRq8T3rVPSke6JSyv5WB8ti4VMi55JRiAdLTCu.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_03_icon_05_miku_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => '42YhauG4BRMhChfzgOjD1FaNyKquMztizrgHINnd.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_03_icon_06_rin_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'md3aEXDWlgPWGXriMjHcTjBsAS466zDsuQMw4vSg.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_04_icon_01_kohane_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'AOsTj3phN1XawYeXkDNa5X62TYdBzuNpJexGBppe.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_04_icon_02_an_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'Eev3mqHoUiVxAH5bjLkowlhsjPo7GaviTVZ6WAbE.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_04_icon_03_akito_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'wa1bErOgyT8B9g3xVtWn55motYvQrud9eRlqZ91d.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_04_icon_04_toya_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'oOSATABJ5kx7oYuCQc5GXrDjB7NMMne5nZ96fQuF.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_04_icon_05_miku_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'dhsEEkhKXnsoTuD72Efz8qYPfjazqIOu587Xozj9.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_04_icon_06_len_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'mKTgVXWh16MkCb3fdBPCWFx53aOfiOqJkw6dCW61.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_04_icon_07_meiko_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => '61qqQpTzttMzi2irqXBrHwCs2igKVQtIehxbyEr2.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_05_icon_01_tsukasa_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => '55MRNBuF02dnQh04AMBlg0kHyu8eGsWBUE8YcGJA.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_05_icon_02_emu_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'mAnzEUFerlKIpZm14mPk2UopPem23AKNB2YISiA2.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_05_icon_03_nene_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'NTjjfth3SmTQLMYC0m6RNuuiUW4uPA6wc2bGGpn3.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_05_icon_04_rui_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'eMAvQqpfvDQmRXHWl4fcMqGKBaIX7oGdXLvFBPdl.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_05_icon_05_miku_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'XMlNcRIm7GInlSyNnlcY6w2NyUi438w3Nk7rG6yM.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_05_icon_06_kaito_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'fqRyWAlbDe0GjhD7XN6LmUOCOo5T1PWbhrkrNDLQ.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_06_icon_01_kanade_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'SntRAAfoNemKnKShSdQPf1G4qe4OEkqu4C45qkR9.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_06_icon_02_mafuyu_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'NTnXAyexbKuD2Jc34453BTVy7rSzCKF5XqbrjvRB.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_06_icon_03_ena_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => 'WOBqxWYm8fiVC7q2yqngUaRuDxi88lS1uJzuAhw5.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_06_icon_04_mizuki_03.jpg',
            ],
            [
                'path' => 'icons',
                'name' => '8BPEHcKyZpA4NohQyHtFEcNyNYHiNhYC8OEhigb1.jpg',
                'mime_type' => 'image/jpeg',
                'extension' => 'jpg',
                'label' => 'unit_06_icon_05_miku_05.jpg',
            ],
        ];

        foreach ($records as $record) {
            $entity = new Icon();
            foreach ($record as $key => $value) {
                $entity->setAttribute($key, $value);
            }
            $entity->save();
        }
    }
}
